title: "Maytronic Systems"
description: "Custom software and technical digital solutions by Maytronic Systems."
baseurl:
url: "https://maytronic-systems.github.io"

markdown: kramdown
permalink: pretty
